# Generated by Django 5.1.1 on 2024-09-24 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nimbus', '0003_comment_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='description',
            field=models.TextField(max_length=255, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='art',
            name='image',
            field=models.ImageField(upload_to='art_images/', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='art',
            name='title',
            field=models.CharField(max_length=80, verbose_name='Título'),
        ),
    ]
